image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixos-19.09
packages:
  - nixpkgs.dafny
  - nixpkgs.mono
  - nixpkgs.z3
sources:
  - git@git.sr.ht:~jorge-jbs/TFG
tasks:
  - check: |
      cd TFG
      sh check.sh
